site_name: Radical spin dynamics


plugins:
  - mkdocs-jupyter:
      execute: false
      include_requirejs: true
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"


# mkdocs.yml
markdown_extensions:
  - pymdownx.snippets:          # enables --8<-- includes
      check_paths: true         # let us point outside the docs dir
  - pymdownx.superfences        # for nice fenced-code handling
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra.css

theme:
    name: material              # but Snippets works with any theme
    features:
        - navigation.footer     # turn on the footer bar
        - content.code.line_numbers
        - content.code.copy
        - content.code.annotate
        - pymdownx.superfences

    icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
